# Generated by Django 4.2.5 on 2023-10-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='nome',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nome do Serviço'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='sigla',
            field=models.CharField(blank=True, max_length=3, verbose_name='Sigla'),
        ),
    ]
