# Generated by Django 4.2.5 on 2023-10-17 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamadosApp', '0003_remove_tipo_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.IntegerField()),
                ('bairro', models.CharField(max_length=50)),
                ('logradouro', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='chamado',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chamado',
            name='prioridade',
            field=models.CharField(choices=[('0', 'Baixa'), ('1', 'Média'), ('2', 'Alta')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('0', 'Aberto'), ('1', 'Pendente'), ('2', 'Resolvido'), ('3', 'Finalizado')], default='0', max_length=1),
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamadosApp.endereco', verbose_name='Endereco')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamadosApp.secretaria', verbose_name='Secretaria')),
            ],
        ),
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('servidor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chamadosApp.servidor')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamadosApp.tipo')),
            ],
            bases=('chamadosApp.servidor',),
        ),
        migrations.AddField(
            model_name='chamado',
            name='secretaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chamadosApp.secretaria', verbose_name='Secretaria'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chamadosApp.setor', verbose_name='Setor'),
        ),
    ]
