# Generated by Django 4.2.5 on 2023-10-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadosApp', '0005_alter_servidor_secretaria_alter_servidor_setor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='endereco',
        ),
        migrations.AddField(
            model_name='setor',
            name='bairro',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='setor',
            name='cep',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='setor',
            name='logradouro',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='setor',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
