# Generated by Django 4.2.5 on 2023-10-19 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamadosApp', '0007_tipo_descricao_remove_atendente_tipo_alter_tipo_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='atendente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atendente', to='chamadosApp.atendente', verbose_name='Atendente'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='requisitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitante', to='chamadosApp.servidor'),
        ),
    ]
