# Generated by Django 4.1.7 on 2023-10-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadosApp', '0009_chamado_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
