# Generated by Django 4.1.7 on 2023-10-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamadosApp', '0012_alter_chamado_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidor',
            name='secretaria',
        ),
    ]
