# Generated by Django 4.2.5 on 2023-10-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadosApp', '0013_remove_servidor_secretaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
