# Generated by Django 4.2.5 on 2023-10-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadosApp', '0014_servidor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='anexo',
            field=models.ImageField(default=None, null=True, upload_to='media/images'),
        ),
    ]
