# Generated by Django 4.2.5 on 2023-10-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadosApp', '0015_chamado_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='anexo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/images'),
        ),
    ]
