# Generated by Django 4.2.5 on 2023-10-25 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamadosApp', '0017_alter_chamado_anexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField(default='')),
                ('confidencial', models.BooleanField(default=False)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamadosApp.chamado', verbose_name='Chamado')),
                ('quemComentou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamadosApp.servidor', verbose_name='quemComentou')),
            ],
        ),
    ]
