# Generated by Django 4.2.5 on 2023-10-31 14:24

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('chamadosApp', '0018_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSInternet',
            fields=[
                ('chamado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chamadosApp.chamado')),
                ('nofcip', models.CharField(max_length=8)),
            ],
            bases=('chamadosApp.chamado',),
        ),
        migrations.CreateModel(
            name='OSSistema',
            fields=[
                ('chamado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chamadosApp.chamado')),
                ('sistema', models.CharField(max_length=50)),
            ],
            bases=('chamadosApp.chamado',),
        ),
        migrations.AddField(
            model_name='servidor',
            name='contato',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
    ]
