# Generated by Django 4.2.5 on 2023-10-31 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamadosApp', '0019_osinternet_ossistema_servidor_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSImpressora',
            fields=[
                ('chamado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chamadosApp.chamado')),
                ('serie', models.CharField(max_length=8)),
                ('contador', models.PositiveIntegerField()),
            ],
            bases=('chamadosApp.chamado',),
        ),
    ]
