# Generated by Django 4.2.5 on 2023-11-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadosApp', '0020_osimpressora'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='matricula',
            field=models.CharField(default='', max_length=6),
        ),
    ]
