# Generated by Django 4.2.5 on 2023-11-10 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamadosApp', '0021_servidor_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='requisitante',
            field=models.ForeignKey(default='Nao existe', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='requisitante', to='chamadosApp.servidor'),
        ),
    ]
