# Generated by Django 4.2.5 on 2023-11-10 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamadosApp', '0022_alter_chamado_requisitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='requisitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitante', to='chamadosApp.servidor'),
        ),
    ]
