# Generated by Django 4.2.5 on 2023-11-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadosApp', '0023_alter_chamado_requisitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='anexo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media\\images'),
        ),
    ]
