# Generated by Django 4.2.5 on 2024-01-17 17:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('chamadosApp', '0024_alter_chamado_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='contato',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='anexo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images'),
        ),
    ]
